In [ ]:
import kagglehub
path = kagglehub.dataset_download("mohammedbahgat/hard-dataset-balanced-reviews")

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


path = "/kaggle/input/hard-dataset-balanced-reviews/balanced-reviews.txt"

df = pd.read_csv(path, sep="\t", header=None, encoding="utf-16", on_bad_lines="skip")
first = df.iloc[0].astype(str).str.strip().str.lower().tolist()
if "sentiment" in first and "review" in first:
    df = df.iloc[1:].reset_index(drop=True)

df = df.iloc[:, :7].copy()

In [ ]:
df

,0,1,2,3,4,5,6
0,no,Hotel name,rating,user type,room type,nights,review
1,2,فندق 72,2,مسافر منفرد,غرفة ديلوكس مزدوجة أو توأم,أقمت ليلة واحدة,“ممتاز”. النظافة والطاقم متعاون.
2,3,فندق 72,5,زوج,غرفة ديلوكس مزدوجة أو توأم,أقمت ليلة واحدة,استثنائي. سهولة إنهاء المعاملة في الاستقبال. ل...
3,16,فندق 72,5,زوج,-,أقمت ليلتين,استثنائي. انصح بأختيار الاسويت و بالاخص غرفه ر...
4,20,فندق 72,1,زوج,غرفة قياسية مزدوجة,أقمت ليلة واحدة,“استغرب تقييم الفندق كخمس نجوم”. لا شي. يستحق ...
...,...,...,...,...,...,...,...
105694,412050,زوار انترناشيونال,1,أسرة,غرفة قياسية توأم,أقمت ليلة واحدة,“فند”. لا شئ عجبني. طقم العمل سيئ جدالا يوجد ب...
105695,412051,زوار انترناشيونال,2,زوج,غرفة ديلوكس توأم,أقمت ليلتين,“سيئ”. قربه من المسجد النبوي الشريف. استخدام م...
105696,412054,زوار انترناشيونال,2,زوج,غرفة قياسية ثلاثية,أقمت ليلة واحدة,“اسوأ إقامة في الرحلة !”. القرب من الحرم. كل ش...
105697,412058,زوار انترناشيونال,2,أسرة,غرفة قياسية رباعية,أقمت 3 ليالي,“دون المستوى”. قربه من الحرم. كل شيء
105698,412059,زوار انترناشيونال,2,أسرة,غرفة قياسية رباعية,أقمت ليلتين,مخيب للأمل. . سوء التنسيق من حيث معرفة الغرف ب...

In [ ]:
negative_data = []
neutral_data = []
positive_data = []
for index, row in df.iterrows():
  if(row[2] in ['1','2']):
    negative_data.append(row[6])
  elif(row[2] in ['3']):
    neutral_data.append(row[6])
  elif(row[2] in ['4','5']):
    positive_data.append(row[6])
print("done")

done

In [ ]:
print(len(negative_data))
print(len(neutral_data))
print(len(positive_data))

52849
0
52849

In [ ]:
print(negative_data[0])
print(positive_data[0])

“ممتاز”. النظافة والطاقم متعاون.
استثنائي. سهولة إنهاء المعاملة في الاستقبال. لاشيئ

In [ ]:
def get_label(row):
  if(row[2] in ['1','2']):
    return -1
  elif(row[2] in ['3']):
    return 0
  else:
    return 1

In [ ]:
reviews = df.iloc[:,6]
labels = df.apply(get_label, axis=1)
new_Data = pd.DataFrame()
new_Data['reviews'] = reviews
new_Data['labels'] = labels
new_Data

                                                  reviews  labels
0                                                  review       1
1                       “ممتاز”. النظافة والطاقم متعاون.       -1
2       استثنائي. سهولة إنهاء المعاملة في الاستقبال. ل...       1
3       استثنائي. انصح بأختيار الاسويت و بالاخص غرفه ر...       1
4       “استغرب تقييم الفندق كخمس نجوم”. لا شي. يستحق ...      -1
...                                                   ...     ...
105694  “فند”. لا شئ عجبني. طقم العمل سيئ جدالا يوجد ب...      -1
105695  “سيئ”. قربه من المسجد النبوي الشريف. استخدام م...      -1
105696  “اسوأ إقامة في الرحلة !”. القرب من الحرم. كل ش...      -1
105697               “دون المستوى”. قربه من الحرم. كل شيء      -1
105698  مخيب للأمل. . سوء التنسيق من حيث معرفة الغرف ب...      -1

[105699 rows x 2 columns]

In [ ]:
negative_reviews = new_Data[new_Data['labels'] == -1].sample(n=5000, random_state=42)
positive_reviews = new_Data[new_Data['labels'] == 1].sample(n=5000, random_state=42)

final_data = pd.concat([negative_reviews, positive_reviews])
final_data = final_data.sample(frac=1, random_state=42).reset_index(drop=True)

display(final_data.head())

                                             reviews  labels
0  جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...       1
1  “حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...      -1
2  “ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...      -1
3  “سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...      -1
4  مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...      -1

In [ ]:
print(f"Shape of the final data: {final_data.shape}")
print("Distribution of labels in final data:")
display(final_data['labels'].value_counts())

Shape of the final data: (10000, 2)
Distribution of labels in final data:

labels
 1    5000
-1    5000
Name: count, dtype: int64

In [ ]:
final_data.to_csv('hotel_reviews.csv', index=False)

In [ ]:
df = pd.read_csv('hotel_reviews.csv')
df

                                                reviews  labels
0     جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...       1
1     “حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...      -1
2     “ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...      -1
3     “سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...      -1
4     مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...      -1
...                                                 ...     ...
9995  جيد جداً. الفندق ممتاز. الذي لم يعجبني عمال وط...       1
9996                                  استثنائي. كل شي.        1
9997                                          “تمام. .        1
9998  “فاشل انحشوا منه ياجماعه والله غلطه سكنت فيه!!...      -1
9999  جيد جداً. . توجد رائحة سيئة في الحمام و سكنت ي...       1

[10000 rows x 2 columns]

In [ ]:
hotel_aspects = {

    "نظافة_الغرفة": {
        "description": "نظافة الغرفة والأثاث",
        "synonyms": [
            "نظافة",
            "النظافة",
            "نظيف",
            "نظيفه",
            "وسخ",
            "متسخ",
            "الغرفة",
            "الغرفه",
            "الغرف",
            "الأوضة",
            "الاوضة"
        ]
    },

    "الحمام": {
        "description": "نظافة وتجهيزات الحمام",
        "synonyms": [
            "الحمام",
            "دورة المياه",
            "التواليت",
            "المروش",
            "الشاور",
            "المغسلة",
            "المياه"
        ]
    },

    "الاستقبال": {
        "description": "خدمة الاستقبال وتسجيل الدخول",
        "synonyms": [
            "الاستقبال",
            "الريسبشن",
            "موظف الاستقبال",
            "الرسبشن",
            "تسجيل الدخول",
            "الدخول",
            "اللوبي"
        ]
    },

    "تعامل_الموظفين": {
        "description": "أسلوب وتعامل العاملين",
        "synonyms": [
            "الموظفين",
            "الموظف",
            "طاقم",
            "العاملين",
            "الخدمة",
            "خدمة",
            "التعامل",
            "تعامل",
            "الخدمات"
        ]
    },

    "الموقع": {
        "description": "موقع الفندق وقربه من الخدمات",
        "synonyms": [
            "الموقع",
            "موقع",
            "المكان",
            "قريب",
            "بعيد",
            "الحرم",
            "المسجد",
            "المولات",
            "المنطقة"
        ]
    },

    "الواي_فاي": {
        "description": "جودة الإنترنت والواي فاي",
        "synonyms": [
            "الواي فاي",
            "واي فاي",
            "wifi",
            "النت",
            "الإنترنت",
            "الانترنت",
            "الشبكة"
        ]
    },

    "الإفطار": {
        "description": "جودة وتنوع الإفطار",
        "synonyms": [
            "الفطور",
            "الافطار",
            "الإفطار",
            "البوفيه",
            "الطعام",
            "الأكل",
            "المطعم"
        ]
    },

    "الأسعار": {
        "description": "السعر والقيمة مقابل المال",
        "synonyms": [
            "السعر",
            "الأسعار",
            "غالي",
            "رخيص",
            "القيمة",
            "السعر مرتفع",
            "السعر مناسب"
        ]
    },

    "مواقف_السيارات": {
        "description": "توفر المواقف وسهولة استخدامها",
        "synonyms": [
            "مواقف",
            "المواقف",
            "السيارات",
            "باركنج",
            "موقف",
            "مواقف السيارات"
        ]
    },

    "السرير": {
        "description": "راحة وجودة السرير",
        "synonyms": [
            "السرير",
            "السرائر",
            "المرتبة",
            "المخدة",
            "الوسادة",
            "النوم"
        ]
    },

    "التكييف": {
        "description": "جودة التكييف ودرجة الحرارة",
        "synonyms": [
            "التكييف",
            "المكيف",
            "المكيفات",
            "بارد",
            "حار",
            "الحرارة"
        ]
    },

    "الهدوء": {
        "description": "الهدوء ومستوى الإزعاج",
        "synonyms": [
            "هادئ",
            "هدوء",
            "إزعاج",
            "ازعاج",
            "ضوضاء",
            "صوت",
            "إزعاجات"
        ]
    },

    "الحجز": {
        "description": "الحجز والإجراءات",
        "synonyms": [
            "الحجز",
            "الحجوزات",
            "بوكينج",
            "الحجز الإلكتروني",
            "التأكيد"
        ]
    },

    "خدمة_الغرف": {
        "description": "الخدمات داخل الغرفة",
        "synonyms": [
            "سيرفس",
            "خدمة الغرف",
            "الخدمة",
            "التنظيف",
            "خدمات الغرف"
        ]
    },

    "الإطلالة": {
        "description": "الإطلالة والمنظر",
        "synonyms": [
            "الإطلالة",
            "الاطلالة",
            "المنظر",
            "الفيو",
            "المشهد"
        ]
    }
}

In [ ]:
detected_aspects_list = []
for index, row in df.iterrows():
    review_text = str(row['reviews'])
    found_aspects = []
    for word in review_text.split():
        for aspect_name, aspect_details in hotel_aspects.items():
            if word in aspect_details['synonyms']:
                found_aspects.append(word)
                break
    detected_aspects_list.append(found_aspects)

df['detected_aspects'] = detected_aspects_list

display(df.head())

,reviews,labels,detected_aspects
0,جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...,1,"[الموقع, الخدمات, الخدمات]"
1,“حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...,-1,"[الانترنت, الانترنت]"
2,“ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...,-1,"[النظافة, الخدمات, الغرف]"
3,“سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...,-1,"[سيرفس, الموظف, الغرفة]"
4,مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...,-1,"[الخدمة, الافطار, الاستقبال, الغرف]"

In [ ]:
df = df[df['detected_aspects'].apply(lambda x: len(x) > 0)]
display(df.head())

,reviews,labels,detected_aspects
0,جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...,1,"[الموقع, الخدمات, الخدمات]"
1,“حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...,-1,"[الانترنت, الانترنت]"
2,“ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...,-1,"[النظافة, الخدمات, الغرف]"
3,“سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...,-1,"[سيرفس, الموظف, الغرفة]"
4,مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...,-1,"[الخدمة, الافطار, الاستقبال, الغرف]"

In [ ]:
print(f"Shape of the DataFrame after dropping rows with empty aspects: {df.shape}")
print("Distribution of labels in the filtered data:")
display(df['labels'].value_counts())

Shape of the DataFrame after dropping rows with empty aspects: (7426, 3)
Distribution of labels in the filtered data:

labels
-1    3856
 1    3570
Name: count, dtype: int64

In [ ]:
import re
from transformers import pipeline
sentiment_pipeline = pipeline("sentiment-analysis", model="CAMeL-Lab/bert-base-arabic-camelbert-da-sentiment")

def get_numerical_aspect_sentiment(row):
    review_text = str(row['reviews'])
    segments = re.split(r'[.\u0640\u060C!\?\n]|\sلكن\s', review_text)
    detected_words = row['detected_aspects']

    sentiment_scores = []

    for word in detected_words:
        relevant_segment = next((s for s in segments if word in s), review_text)

        if len(relevant_segment.strip()) > 2:
            result = sentiment_pipeline(relevant_segment[:512])[0]
            label = result['label'].lower()

            if 'pos' in label:
                sentiment_scores.append(1)
            elif 'neg' in label:
                sentiment_scores.append(-1)
            else:
                sentiment_scores.append(0)
        else:
            sentiment_scores.append(0)

    return sentiment_scores
sample_df = df.head(10).copy()
sample_df['aspect_sentimentality'] = sample_df.apply(get_numerical_aspect_sentiment, axis=1)
display(sample_df[['reviews', 'detected_aspects', 'aspect_sentimentality']])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/841 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/436M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: CAMeL-Lab/bert-base-arabic-camelbert-da-sentiment
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/86.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

,reviews,detected_aspects,aspect_sentimentality
0,جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...,"[الموقع, الخدمات, الخدمات]","[1, 1, 1]"
1,“حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...,"[الانترنت, الانترنت]","[0, 0]"
2,“ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...,"[النظافة, الخدمات, الغرف]","[-1, -1, -1]"
3,“سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...,"[سيرفس, الموظف, الغرفة]","[0, 0, 0]"
4,مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...,"[الخدمة, الافطار, الاستقبال, الغرف]","[0, 0, 0, 0]"
5,استثنائي. الافطار. البعض ياكل من اطباق البوفيه...,[البوفيه],[-1]
6,“مقبول مقابل المال”. اعجبني سعر الفندق. الواي ...,[مواقف],[-1]
9,ضعيف. القرب من الحرم + بوفيه الفندق جيد جداً. ...,"[الحرم, الغرف, نظيفه]","[1, -1, -1]"
10,“سيء جدا”. لا شيء ابدا ولا أنصح به. انتظار ومل...,"[الدخول, الموظف, الاستقبال]","[-1, -1, -1]"
12,جيد جداً. 1- استقبال جيد2- شقه واسعه وتوفير ح...,"[النوم, المروش, الدخول, مواقف, السيارات, غالي]","[1, 1, -1, -1, -1, -1]"

In [ ]:
df['aspect_sentimentality'] = df.apply(get_numerical_aspect_sentiment,axis=1)
df

/tmp/ipykernel_5944/3201678366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['aspect_sentimentality'] = df.apply(get_numerical_aspect_sentiment,axis=1)

,reviews,labels,detected_aspects,aspect_sentimentality
0,جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...,1,"[الموقع, الخدمات, الخدمات]","[1, 1, 1]"
1,“حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...,-1,"[الانترنت, الانترنت]","[0, 0]"
2,“ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...,-1,"[النظافة, الخدمات, الغرف]","[-1, -1, -1]"
3,“سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...,-1,"[سيرفس, الموظف, الغرفة]","[0, 0, 0]"
4,مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...,-1,"[الخدمة, الافطار, الاستقبال, الغرف]","[0, 0, 0, 0]"
...,...,...,...,...
9991,“شكرآ فندق دار الغفران ع الضيافه الاكثر من رائ...,1,"[الاستقبال, الافطار, مواقف, التكييف, النوم, ال...","[1, 1, 0, 0, 0, 0]"
9992,مخيب للأمل. . الغرفه صغيره ليست مطابقه للصور و...,-1,[الغرفه],[-1]
9994,“شقق جيده ولكن تحتاج عنايه أكثر”. تجاوب مالك ا...,1,"[الخدمات, موقع, بوكينج, الحجز]","[0, 0, 0, 0]"
9995,جيد جداً. الفندق ممتاز. الذي لم يعجبني عمال وط...,1,"[نظافة, الغرفة, الاستقبال, الموظف]","[-1, -1, -1, -1]"
9999,جيد جداً. . توجد رائحة سيئة في الحمام و سكنت ي...,1,"[الحمام, خدمة, الغرف, الغرفة]","[-1, -1, -1, -1]"

In [ ]:
df.to_csv("hotel_revies.csv")