In [ ]:
import pandas as pd

combined_df = pd.read_csv("combined_data.csv")
hotel_df = pd.read_csv("hotel_reviews.csv")
hotel_df

,Unnamed: 0,reviews,labels,detected_aspects,aspect_sentimentality
0,0,جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...,1,"['الموقع', 'الخدمات', 'الخدمات']","[1, 1, 1]"
1,1,“حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...,-1,"['الانترنت', 'الانترنت']","[0, 0]"
2,2,“ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...,-1,"['النظافة', 'الخدمات', 'الغرف']","[-1, -1, -1]"
3,3,“سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...,-1,"['سيرفس', 'الموظف', 'الغرفة']","[0, 0, 0]"
4,4,مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...,-1,"['الخدمة', 'الافطار', 'الاستقبال', 'الغرف']","[0, 0, 0, 0]"
...,...,...,...,...,...
7421,9991,“شكرآ فندق دار الغفران ع الضيافه الاكثر من رائ...,1,"['الاستقبال', 'الافطار', 'مواقف', 'التكييف', '...","[1, 1, 0, 0, 0, 0]"
7422,9992,مخيب للأمل. . الغرفه صغيره ليست مطابقه للصور و...,-1,['الغرفه'],[-1]
7423,9994,“شقق جيده ولكن تحتاج عنايه أكثر”. تجاوب مالك ا...,1,"['الخدمات', 'موقع', 'بوكينج', 'الحجز']","[0, 0, 0, 0]"
7424,9995,جيد جداً. الفندق ممتاز. الذي لم يعجبني عمال وط...,1,"['نظافة', 'الغرفة', 'الاستقبال', 'الموظف']","[-1, -1, -1, -1]"
7425,9999,جيد جداً. . توجد رائحة سيئة في الحمام و سكنت ي...,1,"['الحمام', 'خدمة', 'الغرف', 'الغرفة']","[-1, -1, -1, -1]"

In [ ]:
hotel_df = hotel_df[["reviews", "labels"]]

hotel_df.columns = [
    "Sentences_clean",
    "unified_sentiment"
]
hotel_df["domain_name"] = "Hotels"
hotel_df

/tmp/ipykernel_18171/936708932.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["domain_name"] = "Hotels"

,Sentences_clean,unified_sentiment,domain_name
0,جيد. الموقع ممتاز جداً وكل الخدمات متوفرة وقري...,1,Hotels
1,“حلوه بس الانترنت لازم مجانا والفطور يتاخر للس...,-1,Hotels
2,“ليس كل مظهر جيد ان يكون مضمونه جيد والعكس صحي...,-1,Hotels
3,“سيئة”. . نترجاهم يعملو سيرفس وكم مرة اتصل بال...,-1,Hotels
4,مخيب للأمل. . كان يوم زواج ولم احصل على اي شي ...,-1,Hotels
...,...,...,...
7421,“شكرآ فندق دار الغفران ع الضيافه الاكثر من رائ...,1,Hotels
7422,مخيب للأمل. . الغرفه صغيره ليست مطابقه للصور و...,-1,Hotels
7423,“شقق جيده ولكن تحتاج عنايه أكثر”. تجاوب مالك ا...,1,Hotels
7424,جيد جداً. الفندق ممتاز. الذي لم يعجبني عمال وط...,1,Hotels
7425,جيد جداً. . توجد رائحة سيئة في الحمام و سكنت ي...,1,Hotels

In [ ]:
hotel_df = hotel_df[
    [
        "domain_name",
        "unified_sentiment",
        "Sentences_clean"
    ]
]
hotel_df.dropna(inplace=True)

combined_df.dropna(
    subset=["Sentences_clean", "unified_sentiment"],
    inplace=True
)
hotel_df.drop_duplicates(
    subset=["Sentences_clean"],
    inplace=True
)

combined_df.drop_duplicates(
    subset=["Sentences_clean"],
    inplace=True
)

In [ ]:
print("Original Combined Dataset:")
print(combined_df["unified_sentiment"].value_counts())
print("\nHotel Dataset:")
print(hotel_df["unified_sentiment"].value_counts())

Original Combined Dataset:
unified_sentiment
 1.0    4935
-1.0     715
 0.0     405
Name: count, dtype: int64

Hotel Dataset:
unified_sentiment
-1    3854
 1    3569
Name: count, dtype: int64

In [ ]:
final_df = pd.concat(
    [combined_df, hotel_df],
    ignore_index=True
)

In [ ]:
final_df.drop_duplicates(
    subset=["Sentences_clean"],
    inplace=True
)

final_df.reset_index(
    drop=True,
    inplace=True
)
print("\nFinal Dataset Distribution:")
print(final_df["unified_sentiment"].value_counts())

Final Dataset Distribution:
unified_sentiment
 1.0    8504
-1.0    4569
 0.0     405
Name: count, dtype: int64

In [ ]:
final_df.to_csv(
    "combined_with_hotels.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nMerged dataset saved successfully!")

Merged dataset saved successfully!

In [ ]:
final_df

,domain_name,unified_sentiment,Sentences_clean,Aspects_clean,Aspects_sentiments_list,Aspects_list
0,Attractions,1.0,نصحوني بتجربه حمام الكبريت يمكنكم الدخول مع مج...,الحمام، العاملات، الانجليزيه,"[1, 1, -1]","['الحمام', 'العاملات', 'الانجليزيه']"
1,Attractions,1.0,قلعه ساحره منظر خلاب للمدينه من اعلي القلعه يو...,قلعه، منظر، حديقه نباتات، مجري مائي,"[1, 1, 1, 1]","['قلعه', 'منظر', 'حديقه نباتات', 'مجري مائي']"
2,Attractions,1.0,تبليسي جورجيا من اجمل المدن التي زرتها في حيات...,تبليسي جورجيا، شعبها، الحياه,"[1, 1, 1]","['تبليسي جورجيا', 'شعبها', 'الحياه']"
3,Attractions,1.0,جوله علي المدينه القديمه تبليسي شاردن ممتعه ال...,المدينه القديمه تبليسي، الجوله، جلساتها، تلفري...,"[1, 1, 1, 1, 1, 1]","['المدينه القديمه تبليسي', 'الجوله', 'جلساتها'..."
4,Attractions,1.0,احلي اجازه لمحبي الطبيعه المناظر الخلابه الطبي...,اجازه، المناظر، الاجواء، ميزه,"[1, 1, 1, 0]","['اجازه', 'المناظر', 'الاجواء', 'ميزه']"
...,...,...,...,...,...,...
13473,Hotels,1.0,“شكرآ فندق دار الغفران ع الضيافه الاكثر من رائ...,NaN,NaN,NaN
13474,Hotels,-1.0,مخيب للأمل. . الغرفه صغيره ليست مطابقه للصور و...,NaN,NaN,NaN
13475,Hotels,1.0,“شقق جيده ولكن تحتاج عنايه أكثر”. تجاوب مالك ا...,NaN,NaN,NaN
13476,Hotels,1.0,جيد جداً. الفندق ممتاز. الذي لم يعجبني عمال وط...,NaN,NaN,NaN
13477,Hotels,1.0,جيد جداً. . توجد رائحة سيئة في الحمام و سكنت ي...,NaN,NaN,NaN